# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 沿岸踱步
subtitle: 成长日记
description: 沿岸踱步 & 成长记录
keywords: YAN,DUO
author: Yanan^_^Duobu
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## If your site is put in a subdirectory, set url as 'http://example.com/child' and root as '/child/'
# url: http://example.com
url: https://Lklyx.github.io
root: /
# 默认
# permalink: :year/:month/:day/:title/
permalink: :title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: false # edit for Theme.shoka
  line_number: true
  auto_detect: truncate
  tab_replace: ''
prismjs:
  enable: false # edit for Theme.shoka

# Category & Tag
default_category: uncategorized
category_map: 
  ## edit for Theme.shoka
  ## 分类解说：如下面 ① We-Game: ② We-Games。当然不需要更改名字的不用到这里来配置。.md文件中带一张名为cover的图片既可。
  # 都是键值对的方式，左边都是需要显示出来的文字（自己想改的文字），右边则是文件夹的名字。
  # 在md文件中，头部标签中，categories: - [We-Games,英雄联盟,刺客]，categories：是分类的路径，第一个是第一层文件夹改过之后的名字，
  # 也就是分类卡片右上角显示的文字。第二个是第二层文件夹改过之后的名字，也就是分类卡片正中间显示的文字，第三个是卡片翻转以后显示的文字
  # 如果没在分类路径（categories）中添加。如：categories: - [We-Games,英雄联盟,刺客]，则卡片翻转以后直接显示文章的title标题。
  # 注意：必须在.md文件同路径或者上一层路径中添加一张以cover命名的.jpg为后缀名的图片作为分类卡片的背景图。

  We-Games: We-Games # 右上角小标题
  英雄联盟: LOL # 自定义名字：英雄联盟。文件夹名字：LOL
  QQ飞车: QQ飞车

  历练ing: Growth-Diary # 右上角小标题
  Blog: Blog
  WX-小程序: WX-APP

  Diary: Diary # 右上角小标题
  记录生活: 生活
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: shoka # edit for Theme.shoka

# Deployment
## Docs: http://hexo.io/docs/deployment.html

deploy:
  type: 'git'
  # 本次新改
  # repo: 'git@github.com:Lklyx/Lklyx-Lklyx-Lklyx.github.io.git'
  # repo: 'https://github.com/Lklyx/Lklyx.github.io.git'
  repo:  'git@github.com:Lklyx/Lklyx.github.io.git'
  branch: master

# edit for Theme.shoka
autoprefixer:
  exclude:
    - '*.min.css'
markdown:
  render: # 渲染器设置
    html: false # 过滤 HTML 标签
    xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
    breaks: true # 转换段落里的 '\n' 到 <br>。
    linkify: true # 将类似 URL 的文本自动转换为链接。
    typographer:
    quotes: '“”‘’'
  plugins: # markdown-it插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的class名称，shoka主题必须设置成这样
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得有点多了╭(╯^╰)╮"

minify:
  html:
    enable: true
    exclude: # 排除 hexo-feed 用到的模板文件
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    mangle:
    toplevel: true
    output:
    compress:
    exclude:
      - '**/*.min.js'

algolia:
  appId: UPQXMK928J #Your appId
  apiKey: 08f4b02c6106b6f578719816d302a4c9 #Your apiKey
  adminApiKey: e5f3ca76220b66e31b274cf9b3bada2d #Your adminApiKey
  chunkSize: 5000
  indexName: yananduobu
  fields:
    - title # 必须配置
    - path  # 必须配置
    - categories # 推荐配置
    - content:strip:truncate,0,2000
    - gallery
    - photos
    - tags

# 设置博客文章密码
encrypt:
  enable: true
  abstract: 这里有东西被加密了，需要输入密码查看哦。
  message: 请输入密码查看，密码为6位数哦~。
  tags:
  - {name: tagName, password: ziji}
  template: <div id="hexo-blog-encrypt" data-wpm="{{hbeWrongPassMessage}}" data-whm="{{hbeWrongHashMessage}}"><div class="hbe-input-container"><input type="password" id="hbePass" placeholder="{{hbeMessage}}" /><label>{{hbeMessage}}</label><div class="bottom-line"></div></div><script id="hbeData" type="hbeData" data-hmacdigest="{{hbeHmacDigest}}">{{hbeEncryptedData}}</script></div>
  wrong_pass_message: 抱歉, 这个密码看着不太对, 请再试试。
  wrong_hash_message: 抱歉, 这个文章不能被校验, 不过您还是能看看解密后的内容。

# password: ziji
# abstract: 这里有东西被加密了，需要输入密码查看哦。
# message: 请输入密码查看，密码为6位数~。
# wrong_pass_message: 抱歉，这个密码看着不太对，请再试试。
# wrong_hash_message: 抱歉，这个文章不能被纠正，不过您还是能看看解密后的内容。

# 设置博客的宠物
live2d:
  enable: true
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  model:
    # use: live2d-widget-model-hibiki jk小萝莉
    use: live2d-widget-model-koharu # 海军小萝莉
    # use: live2d-widget-model-miku 未来知音小萝莉
    # use: live2d-widget-model-tororo 超可爱的小白猫
    # use: live2d-widget-model-tsumiki 领带小萝莉
    # use: live2d-widget-model-wanko 碗里的小熊
    # use: live2d-widget-model-z16 # 小姐姐
    # use: live2d-widget-model-chitose 绅士男
    # use: live2d-widget-model-gf 动态GF
  display:
    # 设置模型的位置
    position: right
    width: 200
    height: 320
  mobile:
    show: false
  react:
    opacityDefault: 1
    opacityOnHover: 1


feed:
    limit: 20
    order_by: "-date"
    tag_dir: false
    category_dir: false
    rss:
        enable: true
        template: "themes/shoka/layout/_alternate/rss.ejs"
        output: "rss.xml"
    atom:
        enable: true
        template: "themes/shoka/layout/_alternate/atom.ejs"
        output: "atom.xml"
    jsonFeed:
        enable: true
        template: "themes/shoka/layout/_alternate/json.ejs"
        output: "feed.json"